### ISSUE TITLE
`mscorlib` reference assembly is missing `System.Diagnostics.Tracing` methods

### ISSUE THREAD

**Issue by qmfrederik** [mono/reference-assemblies#2]
Commit mono/mono@ce24528b41d28a15feceb4485409d326b8608bc8 added various methods to some of the classes in the `System.Diagnostics.Tracing` namespace. 

This allowed me to run an application on mono.

However, I can currently not compile that application on mono because, from what I gather, the `mscorlib` _reference_  assembly (`mono/4.5-api/mscorlib.dll`) does not contain these updated methods.

I was wondering what the best way would be to fix this? Do I check out `reference-assemblies`, do a binary replacement of mscorlib, and issue a binary PR for that?

Any other recommended approach?

**Comment by marek-safar** [comment]
Could you be more specific what public API you need we are missing there?
Also as the fastest workaround you could upgrade your target framework to .net 4.6 instead of .net 4.5

**Comment by qmfrederik** [comment]
The APIs that are missing are, among others, the various overloads of the `System.Diagnostics.Tracing.EventSource.Write` and `System.Diagnostics.Tracing.EventSource.WriteEvent` method.

I'll try 4.6 and let you know if that helps.

**Comment by Numpsy** [comment]
fwiw, I seem to have a similar issue with the property I added in https://github.com/mono/mono/commit/820b140a1904febb47b256fe3b3b3192cfcac6f9.

Where using the 4.4.0 alpha, the property is found when building against .NET 4.6, but not when building against 4.5. This is only a build issue rather than a runtime issue here, but still, this is a property that's been around for a while.

**Comment by akoeplinger** [comment]
This is (finally) done with https://github.com/mono/reference-assemblies/pull/4 😄
